# Generated by Django 6.0.3 on 2026-03-07 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': '帳號', 'verbose_name_plural': '帳號'},
        ),
    ]
